FROM python:3.9-slim

# Создаем правильный рабочий каталог
WORKDIR /app

# Копируем зависимости
COPY ./parser-bot/bot/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем ВСЕ файлы из папки bot
COPY ./parser-bot/bot .

CMD ["python", "main.py"]