version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: parser
      POSTGRES_DB: parser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parser"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://parser:parser@postgres/parser
      - REDIS_URL=redis://redis:6379/0
      - HH_CLIENT_ID=${HH_CLIENT_ID}
      - HH_CLIENT_SECRET=${HH_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - API_URL=http://api:8000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
  redis_data: