FROM python:3.9-slim

WORKDIR /app

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

# Копируем зависимости и устанавливаем их
COPY ./bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY ./bot .

# Команда запуска
CMD ["python", "main.py"]